# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
  TmpRepoDir: _repo
  UserName: Sint-MNishida
  RepositoryName: si-darts.git

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
      cd /tmp && rm -rf /tmp/$(TmpRepoDir)
      git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" clone --mirror $(Build.Repository.Uri) $(TmpRepoDir)
  displayName: 'clone'

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    cd ./client
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
      git -C /tmp/$(TmpRepoDir) push --mirror https://$(UserName):$(ACCESS_TOKEN)@github.com/$(UserName)/$(RepositoryName)
  displayName: 'Copy to github Repos'